# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make install
      - run: make lint
